#!/bin/bash

########################################################################
####  USER SPECIFIC VARIABLES - CHANGE AS REQUIRED - must be in rbxi-data/
####--------------------------------------------------------------------

# set to either rdiff-backup or rsync. Can be overridden with -o [rm/rs] option
BACKUP_APP='rdiff-backup'

#### BACKUP DIRECTORY PATHS AND INFORMATION -----------
#    << CHANGE TO YOUR BACKUP LOCATION PATHS >>
# Primary backup directory on parition or external drive
# set to your backup partition path
# REMEMBER, DO NOT BACKUP THE BACKUP DIRECTORY, BLOCK IT IN THE EXCLUDE FILE LIST
# Do not end the destination directory  names below with a '/'
# SAMPLE
BACKUP_DIRECTORY='/media/esata'
# set rsync data separately
BACKUP_DIRECTORY_RS='/media/esata'

# Primary backup directories, these will be located inside of the BACKUP_DIRECTORY
# You do not need to create these primary backup directories, the script will do it.
BACKUP_LOCATION='/backup'
BACKUP_LOCATION_RS='/backup-rs'

# for remote, via ssh, include the ssh option
# ie: RSYNC_EXTRA_OPTIONS=' --rsh=ssh ' rsync -e 'ssh -p 30000'
# only set if it's a remote machine, otherwise make null: RSYNC_EXTRA_OPTIONS=''
RSYNC_EXTRA_OPTIONS=' --dry-run -v '
RDIFF_EXTRA_OPTIONS=''

# see man rdiff-backup for proper syntax for time. This is set to remove older
# than 60 days incremental backupsThe time  interval  is  an integer followed
# by the character s, m, h, D, W, M, or Y, indicating seconds, minutes, hours, days,
# weeks, months, or years respectively, or a number of these concatenated.
# For example, 32m  means  32  minutes, and  3W2D10h7s  means 3 weeks, 2 days, 10 hours, and 7 seconds.
RDIFF_REMOVE_TIME='60D'

# specific main backup subdirectory names, eg: /media/usbdisk/bu-2/home and so on
# NOTE: if either of these is left blank, the script will not back up that item.
# You do not need to create the following subdirectories, rdiff-backup will create them
# automatically using the names you give here
BU_HOME='home'
BU_ROOT='root-hda1'

# these are optional backup subdirectories, if these are used the script will backup these
# as well as / and /home autumatically
# Blank '' means the script does not try to back that item up
BU_DATA_1=''
BU_DATA_2=''

#### SYSTEM BACKUP PATH INFORMATION  ------------------
#    << CHANGE TO YOUR SYSTEM PATHS FOR HOME AND / AND EXTRA BACKUP PATHS IF NEEDED >>

# these are the actual directory paths you want to backup
# Should not change these unless you are backing up an install from outside of it
# Note: if you leave off the ending /, rsync will create a directory of the last name in
# the path, which you probably don't want.
USER_HOME_PARENT='/home/'
SYSTEM_ROOT='/'

# these two are optional extra backups, set to absolute path if you are using them
# these correspond to BU_DATA_1 and BU_DATA_2, for example: /home/username/data
USER_DATA_1=''
USER_DATA_2=''

#### SCRIPT OUTPUT STUFF ------------------------------
#    << CHANGE TO YOUR PREFERRED OUTPUT TEXT FOR EXTRA DATA 1/2 BACKUPS >>
# this is only used for backup output text, for user information
USER_DATA_1_DESC='' # for example: USER_DATA_1_DESC=' web'
USER_DATA_2_DESC='' # for example: USER_DATA_2_DESC=' email'

# this is only for print output, it's not used in the actual backup
# << CHANGE TO YOUR ROOT PARTITION FULL PATH >>
ROOT_DESC='/dev/hda1'

# this is how fast the spinning wheel moves. Anything less than 0.5 not
# recommended due to performance problems on most machines.
# Lower number means wheel moves faster. Slower machine, change to 1
SLEEP_TIME_SPINNER='0.5'
# time between backup operations
SLEEP_TIME_BACKUP='2.5'

#### BACKUP DISK / PARITION mount / umount  ------------------
#    << CHANGE TO FIT YOUR NEEDS >>

# if you are not going to be mounting/unmounting your backup partition / disk,
# then set value to blank:
# MOUNT_BU_DISK=""
# UNMOUNT_BU_DISK=""
# Note: you can use anything here, </dev/sdd1>; -L <disk label>; -U <disk uuid>
# replace <....> with your label,uuid, or /dev/...
# Syntax for label: mount -L <disklabel> $BACKUP_DIRECTORY
# Syntax for uuid: mount -U <uuid> $BACKUP_DIRECTORY
# Syntax for standard: mount </dev/sdd2> $BACKUP_DIRECTORY
#
# If you are using NFS mounted directories, the host nfs server must have these permissions set
# in /etc/exports: rw,async,,no_root_squash or write permissions will fail in rsync
#
# SAMPLE:
# rdiff-backup mounts
MOUNT_BU_DISK="mount -L backup-disk-1 $BACKUP_DIRECTORY"
UNMOUNT_BU_DISK="umount $BACKUP_DIRECTORY"

# rsync mounts
MOUNT_BU_DISK_RS="mount -L backup-disk-1 $BACKUP_DIRECTORY_RS"
UNMOUNT_BU_DISK_RS="umount $BACKUP_DIRECTORY_RS"

# these are for options, used in case of cron or option run backups/deletes
# if you want to hard set any option just set the variable to true.
B_DELETED='false' # -d :auto delete contents each backup
B_DO_BACKUP='false' # -b :automatic backup
B_SKIP_MOUNT='false' # -m :do not mount backup drive, or umount it
B_SPINNING_WHEEL='false' # -s :use spinning wheel option
B_TESTING_1='false' # -! 1 :testing flag 1
B_TESTING_2='false' # -! 2 :testing flag 2
